### PR TITLE
Add user guide for deleteorder command

### PR DESCRIPTION
**Pull request by maze508**
Add user guide for deleteorder command

### CODE REVIEW

**Comment by maze508** [comment]
Updated ListOrder Sequence Diagram
updated_listorder_uml
DeleteOrder Sequence Diagram
updated_deleteorder_uml

**Review by sun-ruiheng — APPROVED** [review]
LGTM

**Comment by guanquann** [comment]
For ListOrder, I think its more correct if you call model.getSortedOrder() instead of person.getOrders()?

image

**Comment by maze508** [comment]
updated_listorder_uml2

**Comment by guanquann** [comment]
LGTM

**Pull request merged**
